### ISSUE TITLE
When slide size has changed, the component can't slide down. 

### ISSUE THREAD

**Issue by zhaozhiming** [cmswalker/fullpage-react#1]
HI, 
I dynamic generate `Slide`(Something like as follow), when the `Slide` size change from 2 to 3, the component rerender and I can't slide down to the last `Slide`.
Please help! Thanks.

```
  renderSlides() {
    const { datalist } = this.props;
    return datalist.map((foo, i) => (
      <Slide key={i}>
        <MyComponent foo={foo} />
      </Slide>
    ));
  }

  render() {
    return (
      <Fullpage
        active={this.updateActiveState}
        className={style.main}
      >
        {this.renderSlides()}
      </Fullpage>
    );
  }
```

**Comment by cmswalker** [comment]
Could you post what `MyComponent` looks like?   Slides are 0 indexed and I'm wondering if that could be the case here.  Also, try this and let me know if the slides work:

```renderSlides() {
    const datalist = [0,1,2] ;
    return datalist.map((foo, i) => (
      <Slide key={i}>
        <div key={i}>Hello World.</div>
      </Slide>
    ));
  }

  render() {
    return (
      <Fullpage
        active={this.updateActiveState}
        className={style.main}
      >
        {this.renderSlides()}
      </Fullpage>
    );
  }
```

**Comment by cmswalker** [comment]
This is an interesting Idea. It's now fixed as of 1.0.8, so just `npm install fullpage-react` and you're good to go.  I hadn't though it out as I figured most people would want fairly different slides and would just want to edit them in the `render()` function of Fullpage.  Enjoy!

**Comment by zhaozhiming** [comment]
Thank you, but it seems not publish yet? 

![image](https://cloud.githubusercontent.com/assets/1436694/17647047/03fd32fa-6214-11e6-8d76-0ab13395f7a5.png)

**Comment by cmswalker** [comment]
Haha, whoops

It's up now
