### ISSUE TITLE
onWheel/onDragevent to initiate horizontal scroll

### ISSUE THREAD

**Issue by stevens1434** [cmswalker/fullpage-react#100]
This is my first post and I'm not quite sure how to mark this as a question (mass apologies for that).

I have been trying to implement a way to set up horizontal scrolling via react synthetic events. Included in this would be a wheel event (onWheel) and a mouse event (onDrag). Is there a way to do this with fullpage-react?

Also, is there a onTouch event (for mobile devices) which allows you to move horizontally (both left and right) while you drag the slide. In other words: If, while touching the screen on my phone (onTouch), I move my finger 50% of the way across the screen is it possible to drag the slide 50% of the way across (similar to the swiping effect on Tinder).

Thank you!

**Comment by stevens1434** [comment]
To be more clear on the swipe effect...

Is there a way to move the slide as the user's finger moves rather than: (1) having to swipe; and then (2) remove the finger completely?

**Comment by cmswalker** [comment]
@mahendrushivam please see https://github.com/cmswalker/fullpage-react/pull/104.  Under the new project all fullpage.js APIs are available for the react component

Unfortunately horizontal scrolling via swipe is not supported in that package and this one is no longer maintained in favor of consolidating the 2 projects. If you'd like more native behavior I'd suggest using https://github.com/voronianski/react-swipe as 100% vh and vw divs
