### ISSUE TITLE
Autoscroll

### ISSUE THREAD

**Issue by djflorio** [cmswalker/fullpage-react#101]
Is there a prop to enable autoscroll so that the pages scroll on their own? If not, are there any available methods that would make this possible with a little coding?

**Comment by AAHossny** [comment]
you can follow the same approach used in the example to change the slide manually and change the slide after some time using `setTimeout`

**Comment by cmswalker** [comment]
@djflorio @AAHossny please see https://github.com/cmswalker/fullpage-react/pull/104.  Under the new project all fullpage.js APIs are available for the react component
