### ISSUE TITLE
Using UglifyJS minification breaks counting the number of slides

### ISSUE THREAD

**Issue by ckuijjer** [cmswalker/fullpage-react#11]
We use UglifyJS to minify our JavaScript bundle. During the minification a lot of the variables get renamed, the class Slide would get renamed to e.g. _t_. As the function _getSlideCount_ depends on checking the name of class Slide, it would always return a count of zero and _scrollToSlide_ wouldn't scroll.

I've changed this to compare the type with the Slide class directly in pull request #12

**Comment by cmswalker** [comment]
Fixed in v 15
