### ISSUE TITLE
Keyboard support

### ISSUE THREAD

**Issue by wlingke** [cmswalker/fullpage-react#13]
Is there any plans to support the keyboard down/up arrows?

**Comment by cmswalker** [comment]
Don't see why knot. I'll get it in soon and hit you up when it's ready.

**Comment by wlingke** [comment]
awesome! by the way - really glad there's an active full page react project . It's unfortunate that fullpage.js depends on jquery.

**Comment by cmswalker** [comment]
Now available in `1.0.16`

https://github.com/cmswalker/fullpage-react/commit/5a58d0cc91b1f14c8cc47c796d86ad501265dd64
