### ISSUE TITLE
Removing event listeners doesn't work

### ISSUE THREAD

**Issue by ckuijjer** [cmswalker/fullpage-react#16]
Hey,

We've noticed some odd scrolling behaviour after navigating away from a page with fullpage-react in it. This seems due to the removal of event listeners not working properly. In the `componentDidMount` the functions are first bound to `this` before using them as an event listener. The `componentWillUnmount` however tried to remove the unbound version.

I've tried to solve this in pull request #15 by using the stage-2 [property initializer syntax](http://babeljs.io/docs/plugins/transform-class-properties/) to create autobound versions of e.g. onScroll.

If you don't like to depend on stage-2 features, I'll gladly rewrite this pull request to bind these functions in the constructor.

**Comment by cmswalker** [comment]
Ah i see, yeah an oversight by me. Glad you found this by switching between apps. If you wouldn't mind could you just rewrite the `componentDidUnmount` lifecycle to use binds instead of adding to webpack configs for stage 2?  I'm sure they'll likely be accepted, i'd just rather keep it as vanilla as possible for now.

**Comment by ckuijjer** [comment]
As I understand it binding inside the `componentDidUnmount` like e.g. `    document.removeEventListener('wheel', this.onScroll.bind(this));` wouldn't work, as that would create another bound onScroll function, which wasn't added as an event listener.

I've updated pull request #15 and fixed this by doing the binds in the constructor, like `this.onScroll = this.onScroll.bind(this);`.

P.S. As I did a hard reset to get back to the state before my initial changes, please take a second look.

**Comment by cmswalker** [comment]
fixed in `fullpage-react@1.0.17`

**Comment by ckuijjer** [comment]
Awesome!
