### ISSUE TITLE
Can only update a mounted or mounting component

### ISSUE THREAD

**Issue by bradennapier** [cmswalker/fullpage-react#17]
Can not seem to get this to work, copied your example exactly from what I can tell on Google Chrome.  Not sure what I am missing here.

warning.js:44 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Fullpage component.

**Comment by bradennapier** [comment]
Is there some magic settings that aren't documented to make this work?

Nothing shows up, nothing scrolls, the nav and top nav components do show up - all the "pages" seem to be stacked on top of each other...

**Comment by bradennapier** [comment]
![image](https://cloud.githubusercontent.com/assets/15365418/19582291/0eaa482e-96e8-11e6-9f45-5d55865d2b0c.png)

It is setting the state as it should properly but nothing changes at all when i do it

**Comment by cmswalker** [comment]
try posting your code here and i can help out.

Also feel free to fork it and compare your example with the the one provided when you run `npm start`

I'll update the documentation afterwards too

**Comment by cmswalker** [comment]
marking this closed. will update the docs soon to make things more user friendly. I'll also add a tl;dr section with the bare minimum to get rolling
