### ISSUE TITLE
horizontal scrolling

### ISSUE THREAD

**Issue by cescoferraro** [cmswalker/fullpage-react#18]
I might need to use this repo in the near feature. But would definitely need horizontal scrolling. I could not find a WIP branch, is there one? Have you tried it yet? What are the challenges of doing it?

**Comment by cmswalker** [comment]
Hey there, i do have a WIP branch for this locally, just been tied up at work. Hoping to kick it out within a week or two, will ping back here when it is up

**Comment by cmswalker** [comment]
fixed in V2 https://www.npmjs.com/package/fullpage-react
