### ISSUE TITLE
Clicking a link on touch mode causes scroll

### ISSUE THREAD

**Issue by mehrdaad** [cmswalker/fullpage-react#19]
The title explains itself, package versions:  

     "fullpage-react": "^1.0.18",
       "react": "^15.4.1",
       "react-dom": "^15.4.1"

**Comment by cmswalker** [comment]
So I'm not sure what you're referring to here. Nav links should link such as the ones contained in the demo https://cmswalker.github.io/fullpage-react/

I would recommend using the example in the examples folder or posting your markup here so i can try to replicate it. I put some standard links within slides and there was no scrolling.

**Comment by cmswalker** [comment]
Actually scratch that ^^, looks like it isnt restricted to just links, I there seems to be an override with touch, will fix

**Comment by cmswalker** [comment]
fixed in https://github.com/cmswalker/fullpage-react/pull/20

**Comment by cmswalker** [comment]
@mehrdaad new version is up on npm `1.0.19`

**Comment by cmswalker** [comment]
Actually there are edge cases to this I'm just now realizing due to the event handlers preventing default. Going to re-open this an find a better fix.

**Comment by cmswalker** [comment]
@mehrdaad new version is up as 1.0.20 this actually exposed a pretty funky bug, thanks a ton for finding! https://github.com/cmswalker/fullpage-react/pull/21

**Comment by mehrdaad** [comment]
Your welcome! I appreciate you for fixing it this much fast.  
Another problem(bug) with this lib is that it's not scrolling with mouse-wheel on Firefox, it works with arrow keys though. I tested it on demo page.

**Comment by cmswalker** [comment]
I tested on firefox for mac and android and everything works fine. What version of firefox and on what device?

**Comment by mehrdaad** [comment]
I'm on windows. Firefox version 50.1.0

**Comment by cmswalker** [comment]
ok cool, i'll try to get this running in a VM for windows, they likely have a different event. Any errors in the console?

**Comment by mehrdaad** [comment]
Nope not any error in Firefox.  
Another bad news is it is completely broken on IE 11. the console in IE says: ``HTML1521: Unexpected "</body>" or end of file. All open elements should be closed before the end of the document.
fullpage-react (11,3)``

**Comment by cmswalker** [comment]
@mehrdaad  Let me know if this works now https://cmswalker.github.io/fullpage-react/

**Comment by mehrdaad** [comment]
Not working in Firefox.  
But now works in IE. was the problem related to that page or the lib?

**Comment by mehrdaad** [comment]
Seems like it's time to bump the version again!

**Comment by cmswalker** [comment]
Its the library, will try Firefox Windows again on a VM

**Comment by mehrdaad** [comment]
Did you updat the version to fix the IE problem?

**Comment by cmswalker** [comment]
Yes, the latest version has the IE fix, whatever the demo page is running will always be in-sync with what is up on npm

**Comment by mehrdaad** [comment]
Thanks. By the way, what you think of [this](https://ashojash.com/)

**Comment by cmswalker** [comment]
Very Cool! let me know if you find anything else. Good to see real sites using this! I'll let you know when Firefox is up

**Comment by mehrdaad** [comment]
Sure! Had tested one or two full page libraries before landing on this lib.  
Thanks again.

**Comment by mehrdaad** [comment]
Oh just one more thing, I don't know whether this is a bug or not but when I scroll by scrollbar (Not with mouse-wheel or arrow keys)  the ``currentPage`` state doesn't get updated and I think that relates to the library itself rather than my code. What you think about it?

**Comment by cmswalker** [comment]
ah yes, that is not built in. It could be, i just assumed most people would hide the scroll bar altogether.  It can be done tho

**Comment by mehrdaad** [comment]
Are you planning to develop that as well? and how can I hide scrollbar?

**Comment by cmswalker** [comment]
OK try the demo again for windows Firefox https://cmswalker.github.io/fullpage-react/

I will make an issue to add the scrollbar feature

**Comment by mehrdaad** [comment]
nope, doesn't still work

**Comment by cmswalker** [comment]
Odd it worked on windows 11 firefox 50+ VM.  What windows version are you running?

**Comment by mehrdaad** [comment]
I'm on Windows 10. Do you check it with mouse wheel? because it works with arrow keys but not with mouse wheel.

**Comment by mehrdaad** [comment]
Hi,any updates on this? I tested it just now on Firefox windows.  
It isn't fixed yet apparently.
