### ISSUE TITLE
Not scrolling at all on Firefox

### ISSUE THREAD

**Issue by adamwuyu** [cmswalker/fullpage-react#2]

**Comment by cmswalker** [comment]
This seems to have been working on some older versions but is broken on the latest.  WIll have a look later today

**Comment by adamwuyu** [comment]
Thank you for your quick response. I just found out there are also some error in IE 11. I hope the screenshot can help.
![image](https://cloud.githubusercontent.com/assets/2903328/17668720/3c78d6b4-633d-11e6-9b61-149034ae3adb.png)

**Comment by cmswalker** [comment]
@adamwuyu fixed Firefox as of 1.0.9

Have not fully tested IE yet

**Comment by adamwuyu** [comment]
Great, Firefox works perfectly now!

**Comment by anykao** [comment]
But i still get the same problem in Firfox 48.0 using latest version (fullpage-react@1.0.12).
