### ISSUE TITLE
It shows nothing on IE11

### ISSUE THREAD

**Issue by adamwuyu** [cmswalker/fullpage-react#3]
![image](https://cloud.githubusercontent.com/assets/2903328/17740894/dc6d1366-64cc-11e6-957c-6b5f11b2e8a3.png)

**Comment by cmswalker** [comment]
Looking into this. I'll have to do some synthetic testing as I'm on Unix.  Is it a completely blank page?  

Also, The Warning about unknown props comes from the `react-tappable` library that is a mobile dependency for `fullpage-react`. They're harmless and do not affect anything, the author forgot to remove a few lines of code in their latest `dist/` file but it is being addressed and will be fixed soon.

**Comment by adamwuyu** [comment]
yes, it was total blank. There are another error and some warnings:
![image](https://cloud.githubusercontent.com/assets/2903328/17743971/5fa44fd2-64d8-11e6-86fa-617e344fbdd8.png)

**Comment by cmswalker** [comment]
@adamwuyu fix is up, let me know if the problem persists

**Comment by adamwuyu** [comment]
Hi @cmswalker , I have problem how to visit local node server from windows (there is no index.html, so I don't know how to set it up in Apache...). But I visited the demo page, every thing shows up correctly, but I can not scroll.  Both click and mouse scroll have no response and no new error message  shows up in the console. Here is the warning info from begining:
![image](https://cloud.githubusercontent.com/assets/2903328/17764753/02949424-6554-11e6-9747-d2bf613f7024.png)

**Comment by adamwuyu** [comment]
@cmswalker , and is there a document on how to use this component? There README.md is a little  bit over complicated for me.
