### ISSUE TITLE
how to run example(fullpageReactExample.js)?

### ISSUE THREAD

**Issue by triple1c86** [cmswalker/fullpage-react#31]
Hi, I'm totally a noob in reactjs and webpack.. 
May i know how to run your example(fullpageReactExample.js) in your https://github.com/cmswalker/fullpage-react.git?

this is what i have done so far..
1. git clone https://github.com/cmswalker/fullpage-react.git
2. cd in and npm install
3. npm start - doesnt work.. saying missing webpack-dev-server
4. npm build - nothing as well
5. ./node_modules/.bin/webpack - a static folder comes out.. there's index.js & index.html. double clickin index.html. empty page comes out..

am i doin anything right here? or am i totally goin through the wrong way.. 
Really sorry if this is a stupid question.. i have no clue what im doin here.. would be much appreciated Thanks..

**Comment by cmswalker** [comment]
Looks like I forgot to add it to the dev dependencies. I've just gone over it and made some updates, so you should be good with the newest version from npm `fullpage-react@2.0.2`

https://github.com/cmswalker/fullpage-react/commit/a38be40bfe19732a7fe50de155110f1e88577b4a

Your steps 1-3 should get you running after installing the newest version 

Thanks for finding

**Comment by triple1c86** [comment]
ah sweet! thanks for the fix! 👍
