### ISSUE TITLE
Cant compile. Component missing

### ISSUE THREAD

**Issue by noushad-pp** [cmswalker/fullpage-react#34]
```
Error in ./~/fullpage-react/dist/index.js
Module not found: ./components/HorizontalSlider in /home/user/project/node_modules/fullpage-react/dist
 @ ./~/fullpage-react/dist/index.js 12:29-69
````

I am unable to run I don't even need horizontal scrolling

**Comment by noushad-pp** [comment]
the file name is `horizontalSlider.js `while its trying to load HorizontalSlider.js
```
var HorizontalSliderModule = require('./components/HorizontalSlider');
```

why is this error only happened to me?

**Comment by vetterh1** [comment]
Got this error too.
Dev server was running Windows, so no issue with case.
Compilation failed on Linux though...

**Comment by cmswalker** [comment]
@noushad-pp @vetterh1 could you try the newest version fullpage-react@2.0.3

**Comment by vetterh1** [comment]
fullpage-react@2.0.3 works for me (if not minified, see #35)
Thanks @cmswalker!

**Comment by cmswalker** [comment]
Still looking into uglify compatibility
