### ISSUE TITLE
How enable normal scroll

### ISSUE THREAD

**Issue by Lehakos** [cmswalker/fullpage-react#37]
Hello. I want to enable normal scroll on mobile. Is there any way to do this?

**Comment by cmswalker** [comment]
This can be done, but we'll be at the mercy of parsing the user-agent. Which is most often dependable, but not always.

**Comment by cmswalker** [comment]
@Lehakos  This should now be Resolved in v3

There is a new parameter on options for the breakpoint threshold.

https://www.npmjs.com/package/fullpage-react

**Comment by jnotnull** [comment]
@cmswalker can u tell me which parameter on options ? thanks

**Comment by Alenvee** [comment]
In 3.0.33 don`t find this parameter.
