### ISSUE TITLE
Have fixed content in a horizontal slider

### ISSUE THREAD

**Issue by elverskog** [cmswalker/fullpage-react#40]
I have a use-case that I am having trouble getting to work. I want to have a fixed title above a `HorizontalSlider`; so the main slide title stays in place while the content below slides. 

When I try to embed `HorizontalSlider` inside a `Slide` it causes something in the code to set the `display` of _HorizontalSlider_ to `hide`. I assume it has something to do with it thinking the `HorizontalSlider` is an offscreen slide that should be hidden (or similar?).

As a note - The way I solved this, for now, was to place a ref on the `HorizontalSlider` and get the DOM element to force it to visible when the slide is entered.

**Comment by cmswalker** [comment]
HorizontalSlider should nest its own slides, It should not go inside of Slides.  Basically the structure should be

```
Fullpage ->
    Slide 1 ->
    HorizontalSlider ->
        Slide 1->
        Slide 2 ->
    Slide 2->
```

In v3 this will be much simpler. You'll just pass a Slides Prop to either Fullpage or Horizontal Slide and there won't be any need to worry about refs, but that ^^^ should get you going for now

**Comment by elverskog** [comment]
Thanks but I'm not sure this addresses my exact use-case. When `HorizontalSlider` replaces `Slide` (as you listed) there is no way to have a fixed header above the horizontal slider (as the whole screen slides). I think I'm just looking for something specific (can't please everybody :) . I'm not sure if the passing method you mentioned got the new version will meet this need...but I look forward to checking it out.

**Comment by cmswalker** [comment]
Have you tried making your fixed header a slide with transparent background and higher zIndex?  I will have a working example of your scenario with v3.

**Comment by elverskog** [comment]
Sorry, I'm not sure I follow. I think I would need to see the example you mentioned.

**Comment by cmswalker** [comment]
@elverskog This should now be Resolved in v3
https://www.npmjs.com/package/fullpage-react
