### ISSUE TITLE
"name" doesn't seem to take

### ISSUE THREAD

**Issue by elverskog** [cmswalker/fullpage-react#41]
I'm taking a look at the `onSlideChangeEnd`. The first argument is `name` but when I print `name` it always comes up as "Fullpage". Even though I have the name set to something else in `fullPageOptions` (which is what is passed to the component in my code as in your example). Am I misunderstanding the name parameter is for?

**Comment by cmswalker** [comment]
name is only for horizontal slides. It's for managing state. v3 is almost done and will have better docs I promise

**Comment by elverskog** [comment]
Sounds good. Will keep an eye out. However, Mr. boss-man has set deadlines and I need to launch something by the end of the week so, for now, trying to tweak things (for my specific needs) in your lib as best I can. Like adding `comp.props.name` as an added arg passed to `onSlideChangeEnd` or moving the scroll and touch addEventListeners in `scroll-swipe `to named functions (which worked btw).

So I'm mainly just posting this stuff thinking it may be of value to you to see my weird use cases. Thanks for your quick responses to date. 

Most of my current problems seem to stem from the component not being read as mounted when I go to another /path and then come back to the /path with slides. I'm also then trying to auto-scroll to a specific slide on load (which would be a great feature btw :). E.g. in `jumpScroll` when it sets the state and passes the callback it fails. It can't set the state when it is not mounted, hence the callbacks never happen. 

Again the issue only appears when I go back to the slides. When the page with slides loads fresh everything is roses. It's odd.

**Comment by cmswalker** [comment]
@elverskog This should now be Resolved in v3
https://www.npmjs.com/package/fullpage-react
