### ISSUE TITLE
webpack -p scoll event cannot work

### ISSUE THREAD

**Issue by artkynet** [cmswalker/fullpage-react#43]
when I webpack -p, the scroll event cannot work of release project

**Comment by cmswalker** [comment]
@artkynet Would you mind posting your webpack config here?

The `gh-pages` branch of this repo is running the latest version of fullpage-react with a webpack production build (minified/uglified) and everything is fine.

**Comment by artkynet** [comment]
I use the full page master branch /example to webpack -p，After released , the /static still can't be working with scrolling event

**Comment by cmswalker** [comment]
The example is working when I run it. What happens when you run this?
NODE_ENV=production webpack

**Comment by artkynet** [comment]
@cmswalker now I git clone the new master orgin, run the  `npm run build`, everything looks ok, but I cannot find the dist folder, please help me

**Comment by artkynet** [comment]
@cmswalker the scrolling problem will be report with tomorrow

**Comment by cmswalker** [comment]
The dist folder gets created during the run build script. I'm not sure why you're having a hard time locating it.

**Comment by artkynet** [comment]
@cmswalker when I use `webpack -p` for --optimize-minimize, the scroll event cannot be worked! use `webpack` everything is ok.

**Comment by artkynet** [comment]
@cmswalker now my fullpage-react version is  2.0.3, I will update to 3.0.3, thanks

**Comment by artkynet** [comment]
@cmswalker thanks, resolved!

**Comment by cmswalker** [comment]
Glad you figured it out
