### ISSUE TITLE
Vertical scrolling does not seem to work

### ISSUE THREAD

**Issue by therladbsgh** [cmswalker/fullpage-react#47]
I've tried both the boilerplate and the more detailed example, but in both cases changing the slides vertically (either with a button or with scrolling) does not seem to work. Changing slides horizontally functions as normal.

The code I am using right now (for testing) is identical to the [detailed example.](https://github.com/cmswalker/fullpage-react/blob/master/examples/fullpageReactExample.js) 

Currently using node v6.11.0, npm v3.10.10.

**Comment by cmswalker** [comment]
@therladbsgh post what you have. If its identical it should be working, the example is what will run if you fork this, it is also running in the demo

**Comment by therladbsgh** [comment]
You're right, it seems to work fine when I clone the repo.

Here's my code below. As for dependencies / environment, I've built the project from [mern-starter](https://github.com/Hashnode/mern-starter).

`import React, { PropTypes, Component } from 'react';

const { Fullpage, Slide, HorizontalSlider } = require('fullpage-react');
const { changeFullpageSlide, changeHorizontalSlide } = Fullpage;

// Assets
import style from './css/component.css';

function scrollNavStart(nav) {
  // make the nav fixed when we start scrolling horizontally
  nav.style.position = 'fixed';
}

function scrollNavEnd(nav) {
  // make the nav absolute when scroll finishes
  nav.style.position = 'absolute';
}

const fullPageOptions = {
  // for mouse/wheel events
  // represents the level of force required to generate a slide change on non-mobile, 10 is default
  scrollSensitivity: 7,

  // for touchStart/touchEnd/mobile scrolling
  // represents the level of force required to generate a slide change on mobile, 10 is default
  touchSensitivity: 7,
  scrollSpeed: 500,
  resetSlides: true,
  hideScrollBars: true,
  enableArrowKeys: true,
  breakpoint: 375,
};

const topNavStyle = {
  textAlign: 'center',
  position: 'fixed',
  width: '100%',
  cursor: 'pointer',
  zIndex: 10,
  backgroundColor: 'rgba(255, 255, 255, 0.4)',
  top: '0px',
};

const horizontalNavStyle = {
  position: 'absolute',
  width: '100%',
  top: '50%',
  zIndex: 10,
};

const horizontalSliderProps = {
  name: 'horizontalSlider1',
  infinite: true,
};

class IntroPage extends Component {

  constructor(props) {
    super(props);
    this.state = {
      active: {
        Fullpage: 0,
        horizontalSlider1: 0,
      },
    };

    this.onSlideChangeStart = this.onSlideChangeStart.bind(this);
    this.onSlideChangeEnd = this.onSlideChangeEnd.bind(this);
  }

  componentDidMount() {

  }

  onSlideChangeStart(name, props, state, newState) {
    if (!this.horizontalNav) {
      this.horizontalNav = document.getElementById('horizontal-nav');
    }

    if (name === 'horizontalSlider1') {
      scrollNavStart(this.horizontalNav);
    }
  }

  onSlideChangeEnd(name, props, state, newState) {
    if (name === 'horizontalSlider1') {
      scrollNavEnd(this.horizontalNav);
    }

    const oldActive = this.state.active;
    const sliderState = {
      [name]: newState.activeSlide,
    };

    const updatedState = Object.assign(oldActive, sliderState);
    this.setState(updatedState);
  }

  render() {
    const { active } = this.state;

    const currentActive = active.Fullpage;
    const prevSlide = changeFullpageSlide.bind(null, currentActive - 1);
    const nextSlide = changeFullpageSlide.bind(null, currentActive + 1);
    const goToTop = changeFullpageSlide.bind(null, 1);

    const horizontalSliderName = horizontalSliderProps.name;
    const horizontalActive = this.state.active[horizontalSliderName];

    const prevHorizontalSlide = changeHorizontalSlide.bind(null, horizontalSliderName, horizontalActive - 1);
    const nextHorizontalSlide = changeHorizontalSlide.bind(null, horizontalSliderName, horizontalActive + 1);

    const topNav = (
      <div style={topNavStyle}>
        <span onClick={prevSlide}>
          <button>Previous Slide</button>
        </span>
        <span onClick={goToTop}>
          <button>Back to Top</button>
        </span>
        <span onClick={nextSlide}>
          <button>Next Slide</button>
        </span>
      </div>
    );

    const horizontalNav = (
      <div id="horizontal-nav" style={horizontalNavStyle}>
        <span onClick={prevHorizontalSlide}><button>PREV</button></span>
        <span style={{ position: 'absolute', right: '0px' }} onClick={nextHorizontalSlide}><button>Next</button></span>
      </div>
    );

    const horizontalSlides = [
      <Slide style={{ backgroundColor: 'red' }}><p>Horizontal 1</p></Slide>,
      <Slide style={{ backgroundColor: 'yellow' }}><p>Horizontal 2</p></Slide>,
      <Slide style={{ backgroundColor: 'green' }}><p>Horizontal 3</p></Slide>,
    ];
    horizontalSliderProps.slides = horizontalSlides;

    const horizontalSlider = <HorizontalSlider id="horizontal-slider-1" {...horizontalSliderProps}>{horizontalNav}</HorizontalSlider>;

    const verticalSlides = [
      <Slide style={{ backgroundColor: 'blue' }}>
        <p>Slide 1</p>
      </Slide>,
      horizontalSlider,
      <Slide style={{ backgroundColor: 'pink' }}><p>Slide 3</p></Slide>,
    ];
    fullPageOptions.slides = verticalSlides;

    return (
        <Fullpage onSlideChangeStart={this.onSlideChangeStart} onSlideChangeEnd={this.onSlideChangeEnd} {...fullPageOptions}>
          {topNav}
        </Fullpage>
    );
  }
}

IntroPage.propTypes = {
  toggleIntro: PropTypes.func.isRequired,
};

export default IntroPage;
`

**Comment by cmswalker** [comment]
Interesting, I'll have to try out MERN starter. What you posted above works just fine for me (as long as I omit the css)


```
import React, { PropTypes, Component } from 'react';

import { Fullpage, Slide, HorizontalSlider } from 'fullpage-react';
const { changeFullpageSlide, changeHorizontalSlide } = Fullpage;

function scrollNavStart(nav) {
  // make the nav fixed when we start scrolling horizontally
  nav.style.position = 'fixed';
}

function scrollNavEnd(nav) {
  // make the nav absolute when scroll finishes
  nav.style.position = 'absolute';
}

const fullPageOptions = {
  // for mouse/wheel events
  // represents the level of force required to generate a slide change on non-mobile, 10 is default
  scrollSensitivity: 7,

  // for touchStart/touchEnd/mobile scrolling
  // represents the level of force required to generate a slide change on mobile, 10 is default
  touchSensitivity: 7,
  scrollSpeed: 500,
  resetSlides: true,
  hideScrollBars: true,
  enableArrowKeys: true,
  breakpoint: 375,
};

const topNavStyle = {
  textAlign: 'center',
  position: 'fixed',
  width: '100%',
  cursor: 'pointer',
  zIndex: 10,
  backgroundColor: 'rgba(255, 255, 255, 0.4)',
  top: '0px',
};

const horizontalNavStyle = {
  position: 'absolute',
  width: '100%',
  top: '50%',
  zIndex: 10,
};

const horizontalSliderProps = {
  name: 'horizontalSlider1',
  infinite: true,
};

class IntroPage extends Component {

  constructor(props) {
    super(props);
    this.state = {
      active: {
        Fullpage: 0,
        horizontalSlider1: 0,
      },
    };

    this.onSlideChangeStart = this.onSlideChangeStart.bind(this);
    this.onSlideChangeEnd = this.onSlideChangeEnd.bind(this);
  }

  componentDidMount() {

  }

  onSlideChangeStart(name, props, state, newState) {
    if (!this.horizontalNav) {
      this.horizontalNav = document.getElementById('horizontal-nav');
    }

    if (name === 'horizontalSlider1') {
      scrollNavStart(this.horizontalNav);
    }
  }

  onSlideChangeEnd(name, props, state, newState) {
    if (name === 'horizontalSlider1') {
      scrollNavEnd(this.horizontalNav);
    }

    const oldActive = this.state.active;
    const sliderState = {
      [name]: newState.activeSlide,
    };

    const updatedState = Object.assign(oldActive, sliderState);
    this.setState(updatedState);
  }

  render() {
    const { active } = this.state;

    const currentActive = active.Fullpage;
    const prevSlide = changeFullpageSlide.bind(null, currentActive - 1);
    const nextSlide = changeFullpageSlide.bind(null, currentActive + 1);
    const goToTop = changeFullpageSlide.bind(null, 1);

    const horizontalSliderName = horizontalSliderProps.name;
    const horizontalActive = this.state.active[horizontalSliderName];

    const prevHorizontalSlide = changeHorizontalSlide.bind(null, horizontalSliderName, horizontalActive - 1);
    const nextHorizontalSlide = changeHorizontalSlide.bind(null, horizontalSliderName, horizontalActive + 1);

    const topNav = (
      <div style={topNavStyle}>
        <span onClick={prevSlide}>
          <button>Previous Slide</button>
        </span>
        <span onClick={goToTop}>
          <button>Back to Top</button>
        </span>
        <span onClick={nextSlide}>
          <button>Next Slide</button>
        </span>
      </div>
    );

    const horizontalNav = (
      <div id="horizontal-nav" style={horizontalNavStyle}>
        <span onClick={prevHorizontalSlide}><button>PREV</button></span>
        <span style={{ position: 'absolute', right: '0px' }} onClick={nextHorizontalSlide}><button>Next</button></span>
      </div>
    );

    const horizontalSlides = [
      <Slide style={{ backgroundColor: 'red' }}><p>Horizontal 1</p></Slide>,
      <Slide style={{ backgroundColor: 'yellow' }}><p>Horizontal 2</p></Slide>,
      <Slide style={{ backgroundColor: 'green' }}><p>Horizontal 3</p></Slide>,
    ];
    horizontalSliderProps.slides = horizontalSlides;

    const horizontalSlider = <HorizontalSlider id="horizontal-slider-1" {...horizontalSliderProps}>{horizontalNav}</HorizontalSlider>;

    const verticalSlides = [
      <Slide style={{ backgroundColor: 'blue' }}>
        <p>Slide 1</p>
      </Slide>,
      horizontalSlider,
      <Slide style={{ backgroundColor: 'pink' }}><p>Slide 3</p></Slide>,
    ];
    fullPageOptions.slides = verticalSlides;

    return (
      <Fullpage onSlideChangeStart={this.onSlideChangeStart} onSlideChangeEnd={this.onSlideChangeEnd} {...fullPageOptions}>
        {topNav}
      </Fullpage>
    );
  }
}

IntroPage.propTypes = {
  toggleIntro: PropTypes.func.isRequired,
};

export default IntroPage;
```
