### ISSUE TITLE
Position problem when resize the window.

### ISSUE THREAD

**Issue by adamwuyu** [cmswalker/fullpage-react#5]
Reproduce: Navigate to slide 2, resize window, then the position will not match.
Browser: all browsers.

![image](https://cloud.githubusercontent.com/assets/2903328/17764946/73f24e44-6555-11e6-80a2-b16365a8a023.png)

**Comment by cmswalker** [comment]
fixed https://github.com/cmswalker/fullpage-react/pull/7
