### ISSUE TITLE
Not working since Chrome v61 update

### ISSUE THREAD

**Issue by pixelventures** [cmswalker/fullpage-react#51]
Running the fullpage example on new Chrome 61 doesn't seem to vertical scroll - since update to `document.documentElement.scrollTop`. Tested with v3.0.7

Running through the code still shows scrollTop being assigned increment on every iteration, however, no UI scrolling occurs - not yet sure as to why, sorry. Looking at state within Fullpage component, can confirm active slide is updating and aware of when scrolling is taking place. Reverting to previous scrollTo function in v3.0.4 has no effect.

Same possible issue in Firefox. Chrome v60 runs fine with v3.0.7.

**Comment by cmswalker** [comment]
Will get this fixed in the next day or so

**Comment by pixelventures** [comment]
#52

**Comment by cmswalker** [comment]
fixing in https://github.com/cmswalker/fullpage-react/pull/53

**Comment by cmswalker** [comment]
@pixelventures fixed in fullpage-react@3.0.8  Thanks again
