### ISSUE TITLE
Doesn't work in UIWebView 

### ISSUE THREAD

**Issue by rybyakov** [cmswalker/fullpage-react#56]
I've got an error: 
If you put a link to the website with fullpage-react to an instragram profile and open that link in instagram's in-app browser, the fullpage-react wouldn't work.
I created a simple xcode project with UIWebView and tried to open your demo-site in it and got an error. 
Please have a look. The screenshot is attached.

![screenshot 2017-11-29 21 16 57](https://user-images.githubusercontent.com/10855/33391705-e11c71aa-d54a-11e7-9ed2-63574affd0fe.png)

**Comment by cmswalker** [comment]
@rybyakov thanks for finding this. My experience is pretty limited with in-app browsers and xcode. Could you provide a link showing how I can reproduce this with xcode/UIWebView? I'm guessing/hoping its a missing polyfill

**Comment by rybyakov** [comment]
The best option for debugging this is to use xcode iOS simulator. I attached the project I mentioned before. 
In ViewController.m I put a link to your demo site but you can change it. Push the play button on the xcode's top panel. It will start the iOS simulator and you will see blank screen on it. It is because of the error.
After that you will need to launch Safari (Develop mode must be switched on) and select Develop -> Simulator -> "Page title" (screenshot is attached). It will open Safari Web Inspector and you will get access to the in-app browser's console. Reload the page inside Simulator by pushing reload button in Web Inspector. You will see the error.

That's it. You will be able to debug it.

Sorry for my english, hope I made it clear for you.

![screenshot 2017-11-30 11 35 48](https://user-images.githubusercontent.com/10855/33421357-d1cd166e-d5c2-11e7-99c2-4d09e5bde45a.png)


[WebViewTest.zip](https://github.com/cmswalker/fullpage-react/files/1517005/WebViewTest.zip)

**Comment by cmswalker** [comment]
Thanks again. I believe I have fixed it. Could you verify?  This has however exposed a horizontal scrolling bug (I've replicated it with xcode sim and regular safari) and I will work on it asap.  https://github.com/cmswalker/fullpage-react/issues/57

**Comment by rybyakov** [comment]
Yes!
It works in my project.
Thank you!

**Comment by cmswalker** [comment]
Cool, thanks. Will get that other one handled
