### ISSUE TITLE
Still issue when resize the page

### ISSUE THREAD

**Issue by x86kernel** [cmswalker/fullpage-react#58]
Reproduce: slide to some page, then resize the page 
Result: Still triggering #5 even on https://cmswalker.github.io/fullpage-react/

Browser: chrome

**Comment by cmswalker** [comment]
![fp_rp_gif](https://user-images.githubusercontent.com/8467234/34082831-c7b594c0-e31a-11e7-9da4-0c5eb8239bfa.gif)


Sorry but it seems like its working

**Comment by x86kernel** [comment]
It seems link only working when resize to horizontal
not working when resize to vertical

![Screen](https://i.imgur.com/HgXvgJS.gif)

**Comment by cmswalker** [comment]
ah interesting, ok will look into this
