### ISSUE TITLE
Navigation broken after reload

### ISSUE THREAD

**Issue by tchukuchuk** [cmswalker/fullpage-react#60]
Hi,

I have an issue when I refresh a page with Fullpage component, the navigation is partially broken.

You can see that on your demo (https://cmswalker.github.io/fullpage-react/): 
1. Press DOWN
2. Reload the page
3. Press DOWN or UP : it doesn't work.

**Comment by cmswalker** [comment]
This is related to the other bug reported #59 

Both are fixed in 3.0.20
