### ISSUE TITLE
Server side rendering issue

### ISSUE THREAD

**Issue by buesing** [cmswalker/fullpage-react#63]
Hi, I can't seem to get it to work when using SSR, getting this error:
```
ReferenceError: document is not defined
    at determineVerticalRoot (/Users/moriz/dev/node_modules/fullpage-react/webpack:/lib/components/Fullpage.js:522:5)
    at new Fullpage (/Users/moriz/dev/node_modules/fullpage-react/webpack:/lib/components/Fullpage.js:65:25)
    ...
```
(this is using the next.js framework)

**Comment by buesing** [comment]
Not a public one. It should happen in the next.js boilerplate too.

Michael Walker <notifications@github.com> schrieb am Fr., 12. Jan. 2018 um
17:49 Uhr:

**Comment by cmswalker** [comment]
Addressed https://github.com/cmswalker/fullpage-react/pull/64

**Comment by cmswalker** [comment]
Thanks for finding

`npm i fullpage-react@3.0.23`

**Comment by buesing** [comment]
Fixed, thanks
