### ISSUE TITLE
Error when unmounting

### ISSUE THREAD

**Issue by buesing** [cmswalker/fullpage-react#68]
Got another one. I'm triggering a state change that removes the Fullpage component from the page. When it triggers, I'm getting this error:
```
TypeError: Cannot read property 'bind' of undefined
    at Fullpage.componentWillUnmount 
```
Just by taking a look in the code, there doesn't seem to be a handler called `this.resize` which is being removed at line 319:
```
window.removeEventListener('resize', this.resize.bind(this));
```

**Comment by cmswalker** [comment]
addressed https://github.com/cmswalker/fullpage-react/pull/69

**Comment by cmswalker** [comment]
I would suggest doing a fresh install of `fullpage-react@3.0.26`
