### ISSUE TITLE
Possible to edit path on slide change?

### ISSUE THREAD

**Issue by jasonrhaddix** [cmswalker/fullpage-react#70]
In case I missed it, is it possible to edit the path on slide change  (i.e #slide1, #slide2, etc)?

**Comment by cmswalker** [comment]
It isn't baked in, but it is possible to implement it yourself if desired.

I've updated the docs to better reflect the ability to do this https://github.com/cmswalker/fullpage-react#events-api

Registering callback props as seen here will get you to the point where you could easily plug in push/pop state via the history API for however you want your paths to look https://github.com/cmswalker/fullpage-react/blob/master/examples/fullpageReactExample.js#L145

I could bake it in if there was enough desire for it, but I would rather leave it up to the user to implement as single page routes aren't always easy to agree on.

Let me know if this works for you
