### ISSUE TITLE
Enable overflow-x on div inside <Slide>

### ISSUE THREAD

**Issue by Matt-Owens** [cmswalker/fullpage-react#75]
Is there any way I can enable normal horizontal scrolling (overflow-x: scroll) on a div inside of a slide?

**Comment by cmswalker** [comment]
I looked into this and it would take a considerable amount of work to support it. 

The reason it's complicated is that this library supports horizontal slides by default. There would have to be an option to disable scroll locking on the x Axis for one slide section only, which would be a bit of a pain as it would have to turn back on at some point to link the rest of the layout/state.

I'd say for now, if you don't need a horizontal slide but want overflow behavior on a vertical scroll, use another library that doesn't support horizontal scrolling such as https://github.com/subtirelumihail/react-fullpage

I'm willing to support this if more people need it, but from the sound of it you could get away with using another lib. (unless your design will work as a horizontal slide, in that case go for it!)

**Comment by Matt-Owens** [comment]
@cmswalker Gotcha -- no problem.  Thanks for the work you've done on this library.
