### ISSUE TITLE
Cant scroll when using Firefox

### ISSUE THREAD

**Issue by anykao** [cmswalker/fullpage-react#8]
Firfox 48.0
fullpage-react@1.0.12

**Comment by cmswalker** [comment]
This seems to be working fine. Did you look at the demo page in firefox 48? https://cmswalker.github.io/fullpage-react/

**Comment by cmswalker** [comment]
This seems to be working fine in firefox 48.  Did you look at the demo in firefox? https://cmswalker.github.io/fullpage-react/

If that works but your build doesn't post your options here and I'll try to help

**Comment by anykao** [comment]
Yes, I tried  the Demo page, and didn't work there.
Maybe  I should mention that I'm using ubuntu.

**Comment by cmswalker** [comment]
@anykao Could you take a screenshot of any errors in the firefox console that may appear when you go to the demo page?
