### ISSUE TITLE
our build script complains about global innerWidth

### ISSUE THREAD

**Issue by makc** [cmswalker/fullpage-react#80]
you are missing
> const { innerWidth } = this.state.window;

there somewhere

**Comment by cmswalker** [comment]
"build script" as in a linter, transpiler? Can you post a stacktrace or screenshot?

**Comment by cmswalker** [comment]
Fixed in `3.0.30`

**Comment by makc** [comment]
Idk why I never receive notifications from this project. The build cript, I think, was "react-scripts build"
