### ISSUE TITLE
Examples/approaches for canceling then resuming sliding?

### ISSUE THREAD

**Issue by robbiew** [cmswalker/fullpage-react#86]
Trying to figure this out: how to stop a slide, fade out the slide, then resume the sliding to next slide.

> Sliding can be cancelled in the event that you want the user to stay fixed on a slide for some reason. If the function passed to onSlideChangeStart returns true, sliding can be cancellabe until it returns falsy.

New to React, this is how I've done it in fullpage.js/jQuery with callbacks onLeave event. Is the approach similar with full=page react?
```

if (index == 1 && nextIndex == 2) {
        var curTime = new Date().getTime();
        $('#video-background').css({
          'opacity': '0',
          'transition': 'all .3s ease-out'
        });
        $('.home').css({
          'opacity': '0',
          'transition': 'all .3s ease-out'
        });
        this.clearTimeout(timeoutId);
        timeoutId = setTimeout(function () {
          animationIsFinished = true;
          $.fn.fullpage.moveTo(nextIndex);
        }, delay);
        return animationIsFinished;
      }
```

**Comment by cmswalker** [comment]
You'd be able to use your old implementation if we go this route https://github.com/cmswalker/fullpage-react/issues/83 let me know how you feel about it

**Comment by cmswalker** [comment]
This will be handled via https://github.com/cmswalker/fullpage-react/issues/90
