### ISSUE TITLE
Slide Background Colors

### ISSUE THREAD

**Issue by V1shvesh** [cmswalker/fullpage-react#87]
Similar to sectionColors option in fullpage.js, can we have slideColors option here?

**Comment by cmswalker** [comment]
Thinking about fully wrapping that lib to provide all the APIs for free, please see https://github.com/cmswalker/fullpage-react/issues/83 and add feedback if you have any

**Comment by cmswalker** [comment]
This will be handled via https://github.com/cmswalker/fullpage-react/issues/90
