### ISSUE TITLE
iOS 9 problem

### ISSUE THREAD

**Issue by makc** [cmswalker/fullpage-react#88]
[this line](https://github.com/cmswalker/fullpage-react/blob/6086cc079a1fbcee8778d5728dc396ca5c97518c/lib/components/Fullpage.js#L173) causes this error:
![screen shot 2018-05-21 at 2 39 38](https://user-images.githubusercontent.com/242577/40285423-7af933a4-5ca4-11e8-881e-16317d11aa76.png)

fx:
> let path = startEvent.path || (startEvent.composedPath ? startEvent.composedPath() : null);

**Comment by cmswalker** [comment]
fixed in 3.0.32
