### ISSUE TITLE
Scroll is locked after component using fullpage-react unmounts

### ISSUE THREAD

**Issue by dstrekelj** [cmswalker/fullpage-react#92]
Hello,

I'm having trouble using `fullpage-react` across pages with different scroll behaviours. I'll try to be as concise as possible when describing my issue. Hopefully it's just something I'm doing wrong.

## Use case

I'm working on a website where the landing page needs to be presented in a fullpage-like fashion - every page section is a "slide" covering the entire browser viewport. Other pages making up the website aren't as specific - normal scroll behaviour should apply here, as sections are of varying heights.

## Example

The relevant project dependencies are:

* `react 16.3.2`
* `react-router 4.2.2` 
* `fullpage-react 3.0.32`

The project structure is roughly as follows:

**App.jsx**
```jsx
import React from 'react';
import { Switch, Route } from 'react-router';

import { LandingPage } from 'routes/LandingPage';
import { ProductsPage } from 'routes/ProductsPage';
import { NotFoundPage } from 'routes/NotFoundPage';

export class App extends React.Component {
  render() {
    return (
      <Switch>
        <Route exact path="/products" component={ProductsPage} />
        <Route exact path="/" component={LandingPage} />
        <Route component={NotFoundPage} />
      </Switch>
    );
  }
}

export default App;
```

**LandingPage.jsx**
```jsx
import React from 'react';
import { Fullpage, Slide } from 'fullpage-react';

import * as Section from 'components/Section';

const fullpageOptions = {
    scrollSpeed: 400,
    resetSlides: true,
    hideScrollBars: true,
    enableArrowKeys: true,
    activeSlide: 0,
}

export class LandingPage extends React.Component {
  render() {
    return (
      <div>
        <Fullpage {...fullpageOptions}
          slides={[
            <Section.HeroSection />
            <Section.ProductsSection />
            <Section.AboutSection />
            <Section.ContactSection />
          ].map(section => <Slide>{section}</Slide>}
        />
      </div>
    );
  }
}

export default LandingPage;
```

The other pages do not use the `<Fullpage>` or `<Slide>` components.

## Expected behaviour

Changing routes begets a full page change, which in turn means the previous page component is unmounted and the next one is mounted. I expected that unmounting a component which uses `fullpage-react` functionality would also remove all hold it has on browser scroll behaviour.

I expected that - by switching from a page with assisted scrolling to a page without it - the scrolling action would behave normally on the pages where `fullpage-react` isn't used. Currently, it seems like the default behaviour remains prevented, and no new behaviour is installed in its place.

## Observed behaviour

After switching from the landing page to other pages with no `fullpage-react` assisted scrolling, the scroll action isn't functional - scrolling is completely locked. I cannot scroll with the mouse or the keyboard.

I noticed that the document `<body>` element of pages navigated to from the landing page has an inline `overflow: hidden` style attribute attached to it. This seems to be left over from `fullpage-react` on the landing page, which leads me to believe that some clean-up code may not be functioning correctly when `<Fullpage>` or relevant components are unmounted.

## Request

I'm aware that the new jQuery-less `fullpage.js` is right around the corner, but this seems to be a bug worth patching for this version of `fullpage-react`. I believe it would be useful to mix-and-match scroll behaviours from page to page, and that side-effects from using `fullpage-react` (if this really is the case) shouldn't bleed into components that don't use it.

Thank you for your time and work on this very useful React component!

Regards,

Domagoj

**Comment by dstrekelj** [comment]
As documented in the commit message, the issue was that the effect of the `hideScrollBars` option was not taken into account when cleaning up on `<Fullpage>` component unmounting. The proposed change merely calls `showScrollBars()` under the right conditions so that the scroll bars appear afterwards.

**Comment by dstrekelj** [comment]
@cmswalker Yup, everything works as expected now :)

**Comment by cmswalker** [comment]
👍 thanks for your submission
