### ISSUE TITLE
Importing 'import 'semantic-ui-css/semantic.min.css' breaks module

### ISSUE THREAD

**Issue by dbarabander** [cmswalker/fullpage-react#95]
Hey @cmswalker love this library, by the far the best I've found for full page scroll.

It's not necessarily your problem, but when I add the following line to  import 'semantic-ui-css/semantic.min.css'; to index.js (on a standard CRA repo) this module no longer works (scrolling of any sort is disabled, etc).

Just something I thought you might want to be aware of!

**Comment by cmswalker** [comment]
Thanks for posting this, i'm guessing semantic ui is doing something special with overflow properties? To be honest it probably won't be addressed in favor of https://github.com/cmswalker/fullpage-react/issues/90. I'll post back here once that is complete to see if there are still issues
