### ISSUE TITLE
Now working with domestic browsers

### ISSUE THREAD

**Issue by thearnica** [cmswalker/fullpage-react#97]
Hey! Kudos for the library. It is the only "full page" for react, which actually works.
Unfortunately - it does not work for all the cases.

To be more concrete - for vast majority of Chrome clones, which are _chrome_, but provide a different UserAgent.

Result is always the same - document.body is picked instead of document element, and scroll literally dies.

Would you consider using `window.scrollTo`, instead of `scrollTop` on some element?
It could simplify the code, and works everywhere.

**Comment by thearnica** [comment]
For now I have to _polyfill_ it
```js
Object.defineProperty(document.body, 'scrollTop', {
  set: value => window.scrollTo(0,value),
  get: () => window.scrollY
});
```

And it works for me.

**Comment by cmswalker** [comment]
Hi Marina, thanks for finding a polyfill. I'll be sure to include this for the final patch. In the meantime please see https://github.com/cmswalker/fullpage-react/issues/90 as this will soon be deprecated

**Comment by cmswalker** [comment]
@thearnica  please see #104. Under the new project all fullpage.js APIs are available for the react component
