### ISSUE TITLE
Horizontal slider scroll navigation not scrolling on iOS

### ISSUE THREAD

**Issue by pushbuttons** [cmswalker/fullpage-react#98]
Tested on:

iPhone X iOS 11.4 Safari
iPhone X iOS 11.4 Chrome 67.0.339.857
iPad Pro 10.5 iOS 11.4 Safari
iPad Pro 10.5 iOS 11.4 Chrome 67.0.339.857

Horizontal slider scroll navigation working on Android 8.0 (Galaxy S7) Chrome 67.0.339.857

Temporary work around - button navigation for next and prev on iOS.

**Comment by cmswalker** [comment]
@pushbuttons  please see #104. Under the new project all fullpage.js APIs are available for the react component. There should be much better browser compatibility now
